version: '3'
services:
  web:
    container_name: app
    build: ./nginx
    # ホストの8080番ポートをkoコンテナの80番ポートにマッピングする
    ports:
      - "8080:80"
    # ホストとコンテナのディレクトリのマウントを指定
    volumes:
      - ./nginx/src:/usr/share/nginx/html