version: '3'
services:
  web:
    container_name: app
    build: ./nginx
    image: app:0.0.1
    # ホストの8080番ポートをkoコンテナの80番ポートにマッピングする
    ports:
      - "8080:80"
    # ホストとコンテナのディレクトリのマウントを指定
    volumes:
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/src:/usr/share/nginx/html